<%@ Page Title="" Language="C#" Async="true" MasterPageFile="~/Masters/Logged.Master" AutoEventWireup="true" CodeBehind="Delete.aspx.cs" Inherits="VirtualRobot.Vistas.Logeado.Delete" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <tspan x="0" y="18" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Deletion of this account will result in loss of ALL content associated with it, which may<span>&nbsp;</span></tspan><tspan x="0" y="40" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">include the following:</tspan><tspan x="0" y="62" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"></tspan><tspan x="0" y="84" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"></tspan><tspan x="0" y="106" xml:space="preserve" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><br />
&nbsp;<asp:BulletedList ID="BulletedList1" runat="server">
        <asp:ListItem>Any existing funds usable through this account</asp:ListItem>
        <asp:ListItem>Software, and items purchased via this Virtual Robot Account</asp:ListItem>
        <asp:ListItem>The ability to redownload any digital software purchased by / linked to this account</asp:ListItem>
        <asp:ListItem>Save/user data of any apps linked to this account</asp:ListItem>
    </asp:BulletedList>
    </tspan>
    <tspan font-size="20" font-family="SegoeUI-Bold, Segoe UI" font-weight="700" style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    <h1 x="0" y="239">What is our process for account deletion?</h1>
    <br />
    </tspan></tspan><tspan x="0" y="262" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"></tspan><tspan x="0" y="284" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">After 
    choosing to delete a Virtual Robot Account, it will be deactivated for 15 days before<span>&nbsp;</span></tspan><tspan x="0" y="306" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">being deleted, during which time you can reactivate it by attempting to sign in. The<span>&nbsp;</span></tspan><tspan x="0" y="328" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">account 
    will be deleted permanently after the deactivation period passes.</tspan><tspan x="0" y="350" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"></tspan><tspan x="0" y="372" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><br />
    <br />
    To reactivate an account that has been set for deletion, you 
    need the password and e-mail<span>&nbsp;</span></tspan><tspan x="0" y="394" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">address you use to sign in to your account. If you haven&#39;t verified your e-mail address, you<span>&nbsp;</span></tspan><tspan x="0" y="416" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">won&#39;t 
    be able to retrieve your password if you forget it. Please verify your e-mail address in<span>&nbsp;</span></tspan><tspan x="0" y="438" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">case you want to reactivate this account.<br />
    <br />
    </tspan><tspan x="0" y="460" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"></tspan><tspan x="0" y="482" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">If 
    you choose to reactivate an account during the deactivation period, we cannot<span>&nbsp;</span></tspan><tspan x="0" y="504" style="color: rgb(0, 0, 0); font-family: SegoeUI, &quot;Segoe UI&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">guarantee that all of the data will be recovered</tspan><br />
    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Back" />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Delete Account" />
</asp:Content>
