//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRobot.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugador()
        {
            this.Currency_Jugador = new HashSet<Currency_Jugador>();
            this.Jugador_Amigo = new HashSet<Jugador_Amigo>();
            this.Jugador_IP = new HashSet<Jugador_IP>();
            this.Juegos = new HashSet<Juegos>();
        }
    
        public int idJugador { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
        public string passwordHash { get; set; }
        public string passwordSalt { get; set; }
        public System.DateTime fecNacimiento { get; set; }
        public string genero { get; set; }
        public string paisResidencia { get; set; }
        public string fecUltimaConexion { get; set; }
        public string timeZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Currency_Jugador> Currency_Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador_Amigo> Jugador_Amigo { get; set; }
        public virtual Jugador_Amigo Jugador_Amigo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugador_IP> Jugador_IP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Juegos> Juegos { get; set; }
    }
}
